title:              MY PORTFOLIO
email:              issawandhe@gmail.com
description:        portfolio for toitek
author:             toitek
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://toitek.github.io"

# Social Profiles
twitter_username:   tec_toi
github_username:    toitek
facebook_username:  toitek
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
